<?php

namespace Database\Seeders;

use App\Models\Admission;
use Illuminate\Database\Seeder;

class AdmissionSeeder extends Seeder
{
    public function run(): void
    {
        $demoStudents = [
            [
                'admission_no' => 'ADM-2026-001',
                'first_name' => 'Muhammad',
                'last_name' => 'Ali',
                'cnic_bform' => '35202-1234567-1',
                'date_of_birth' => '2015-05-12',
                'gender' => 'Male',
                'father_name' => 'Tariq Mahmood',
                'guardian_name' => 'Tariq Mahmood',
                'guardian_relation' => 'Father',
                'guardian_cnic' => '35202-9876543-1',
                'guardian_primary_mobile_no' => '03001234567',
                'class_name' => 'Class 5',
                'section_name' => 'A',
                'roll_no' => '101',
                'monthly_fee' => 4500,
                'current_address' => 'Gulberg III, Lahore',
                'emergency_contact_name' => 'Tariq Mahmood',
                'emergency_contact_relation' => 'Father',
                'emergency_contact_mobile_no' => '03001234567',
                'admission_status' => 'approved',
                'admission_date' => '2026-01-15',
                'is_confirmed' => true,
            ],
            [
                'admission_no' => 'ADM-2026-002',
                'first_name' => 'Fatima',
                'last_name' => 'Zahra',
                'cnic_bform' => '35202-2345678-2',
                'date_of_birth' => '2016-08-20',
                'gender' => 'Female',
                'father_name' => 'Shahid Khan',
                'guardian_name' => 'Shahid Khan',
                'guardian_relation' => 'Father',
                'guardian_cnic' => '35202-8765432-2',
                'guardian_primary_mobile_no' => '03219876543',
                'class_name' => 'Class 4',
                'section_name' => 'B',
                'roll_no' => '102',
                'monthly_fee' => 4000,
                'current_address' => 'Model Town, Lahore',
                'emergency_contact_name' => 'Shahid Khan',
                'emergency_contact_relation' => 'Father',
                'emergency_contact_mobile_no' => '03219876543',
                'admission_status' => 'approved',
                'admission_date' => '2026-01-18',
                'is_confirmed' => true,
            ],
            [
                'admission_no' => 'ADM-2026-003',
                'first_name' => 'Ahmed',
                'last_name' => 'Raza',
                'cnic_bform' => '35202-3456789-3',
                'date_of_birth' => '2014-02-10',
                'gender' => 'Male',
                'father_name' => 'Usman Raza',
                'guardian_name' => 'Usman Raza',
                'guardian_relation' => 'Father',
                'guardian_cnic' => '35202-7654321-3',
                'guardian_primary_mobile_no' => '03334567890',
                'class_name' => 'Class 6',
                'section_name' => 'A',
                'roll_no' => '103',
                'monthly_fee' => 5000,
                'current_address' => 'Johar Town, Lahore',
                'emergency_contact_name' => 'Usman Raza',
                'emergency_contact_relation' => 'Father',
                'emergency_contact_mobile_no' => '03334567890',
                'admission_status' => 'approved',
                'admission_date' => '2026-01-20',
                'is_confirmed' => true,
            ],
            [
                'admission_no' => 'ADM-2026-004',
                'first_name' => 'Zainab',
                'last_name' => 'Noor',
                'cnic_bform' => '35202-4567890-4',
                'date_of_birth' => '2017-11-05',
                'gender' => 'Female',
                'father_name' => 'Bilal Ahmed',
                'guardian_name' => 'Bilal Ahmed',
                'guardian_relation' => 'Father',
                'guardian_cnic' => '35202-6543210-4',
                'guardian_primary_mobile_no' => '03456789012',
                'class_name' => 'Class 3',
                'section_name' => 'A',
                'roll_no' => '104',
                'monthly_fee' => 3800,
                'current_address' => 'DHA Phase 5, Lahore',
                'emergency_contact_name' => 'Bilal Ahmed',
                'emergency_contact_relation' => 'Father',
                'emergency_contact_mobile_no' => '03456789012',
                'admission_status' => 'approved',
                'admission_date' => '2026-02-01',
                'is_confirmed' => true,
            ],
            [
                'admission_no' => 'ADM-2026-005',
                'first_name' => 'Hamza',
                'last_name' => 'Hassan',
                'cnic_bform' => '35202-5678901-5',
                'date_of_birth' => '2013-07-25',
                'gender' => 'Male',
                'father_name' => 'Hassan Farooq',
                'guardian_name' => 'Hassan Farooq',
                'guardian_relation' => 'Father',
                'guardian_cnic' => '35202-5432109-5',
                'guardian_primary_mobile_no' => '03012345678',
                'class_name' => 'Class 8',
                'section_name' => 'B',
                'roll_no' => '105',
                'monthly_fee' => 6000,
                'current_address' => 'Faisal Town, Lahore',
                'emergency_contact_name' => 'Hassan Farooq',
                'emergency_contact_relation' => 'Father',
                'emergency_contact_mobile_no' => '03012345678',
                'admission_status' => 'approved',
                'admission_date' => '2026-02-05',
                'is_confirmed' => true,
            ],
            [
                'admission_no' => 'ADM-2026-006',
                'first_name' => 'Ayesha',
                'last_name' => 'Siddiqua',
                'cnic_bform' => '35202-6789012-6',
                'date_of_birth' => '2012-03-14',
                'gender' => 'Female',
                'father_name' => 'Muhammad Imran',
                'guardian_name' => 'Muhammad Imran',
                'guardian_relation' => 'Father',
                'guardian_cnic' => '35202-4321098-6',
                'guardian_primary_mobile_no' => '03123456789',
                'class_name' => 'Class 9',
                'section_name' => 'A',
                'roll_no' => '106',
                'monthly_fee' => 6500,
                'current_address' => 'Garden Town, Lahore',
                'emergency_contact_name' => 'Muhammad Imran',
                'emergency_contact_relation' => 'Father',
                'emergency_contact_mobile_no' => '03123456789',
                'admission_status' => 'approved',
                'admission_date' => '2026-02-10',
                'is_confirmed' => true,
            ],
            [
                'admission_no' => 'ADM-2026-007',
                'first_name' => 'Ibrahim',
                'last_name' => 'Khalil',
                'cnic_bform' => '35202-7890123-7',
                'date_of_birth' => '2011-09-30',
                'gender' => 'Male',
                'father_name' => 'Khalil Ur Rehman',
                'guardian_name' => 'Khalil Ur Rehman',
                'guardian_relation' => 'Father',
                'guardian_cnic' => '35202-3210987-7',
                'guardian_primary_mobile_no' => '03234567890',
                'class_name' => 'Class 10',
                'section_name' => 'A',
                'roll_no' => '107',
                'monthly_fee' => 7000,
                'current_address' => 'Iqbal Town, Lahore',
                'emergency_contact_name' => 'Khalil Ur Rehman',
                'emergency_contact_relation' => 'Father',
                'emergency_contact_mobile_no' => '03234567890',
                'admission_status' => 'approved',
                'admission_date' => '2026-02-12',
                'is_confirmed' => true,
            ],
            [
                'admission_no' => 'ADM-2026-008',
                'first_name' => 'Maryam',
                'last_name' => 'Jameel',
                'cnic_bform' => '35202-8901234-8',
                'date_of_birth' => '2018-04-18',
                'gender' => 'Female',
                'father_name' => 'Jameel Akhtar',
                'guardian_name' => 'Jameel Akhtar',
                'guardian_relation' => 'Father',
                'guardian_cnic' => '35202-2109876-8',
                'guardian_primary_mobile_no' => '03345678901',
                'class_name' => 'Class 2',
                'section_name' => 'A',
                'roll_no' => '108',
                'monthly_fee' => 3500,
                'current_address' => 'Wapda Town, Lahore',
                'emergency_contact_name' => 'Jameel Akhtar',
                'emergency_contact_relation' => 'Father',
                'emergency_contact_mobile_no' => '03345678901',
                'admission_status' => 'approved',
                'admission_date' => '2026-02-15',
                'is_confirmed' => true,
            ],
            [
                'admission_no' => 'ADM-2026-009',
                'first_name' => 'Bilal',
                'last_name' => 'Zubair',
                'cnic_bform' => '35202-9012345-9',
                'date_of_birth' => '2015-12-01',
                'gender' => 'Male',
                'father_name' => 'Zubair Malik',
                'guardian_name' => 'Zubair Malik',
                'guardian_relation' => 'Father',
                'guardian_cnic' => '35202-1098765-9',
                'guardian_primary_mobile_no' => '03467890123',
                'class_name' => 'Class 5',
                'section_name' => 'B',
                'roll_no' => '109',
                'monthly_fee' => 4500,
                'current_address' => 'Samanabad, Lahore',
                'emergency_contact_name' => 'Zubair Malik',
                'emergency_contact_relation' => 'Father',
                'emergency_contact_mobile_no' => '03467890123',
                'admission_status' => 'approved',
                'admission_date' => '2026-02-18',
                'is_confirmed' => true,
            ],
            [
                'admission_no' => 'ADM-2026-010',
                'first_name' => 'Hafsa',
                'last_name' => 'Tariq',
                'cnic_bform' => '35202-0123456-0',
                'date_of_birth' => '2014-06-14',
                'gender' => 'Female',
                'father_name' => 'Tariq Jamil',
                'guardian_name' => 'Tariq Jamil',
                'guardian_relation' => 'Father',
                'guardian_cnic' => '35202-0987654-0',
                'guardian_primary_mobile_no' => '03023456789',
                'class_name' => 'Class 7',
                'section_name' => 'A',
                'roll_no' => '110',
                'monthly_fee' => 5500,
                'current_address' => 'Township, Lahore',
                'emergency_contact_name' => 'Tariq Jamil',
                'emergency_contact_relation' => 'Father',
                'emergency_contact_mobile_no' => '03023456789',
                'admission_status' => 'approved',
                'admission_date' => '2026-02-20',
                'is_confirmed' => true,
            ],
        ];

        foreach ($demoStudents as $data) {
            Admission::updateOrCreate(['admission_no' => $data['admission_no']], $data);
        }

        if (Admission::count() < 50) {
            Admission::factory()->count(100)->create();
        }

        Admission::all()->each(function ($adm) {
            $adm->save();
        });
    }
}
