<?php

namespace Database\Seeders;

use App\Models\Inventory;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class InventorySeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'item_code'          => 'INV-IT-101',
                'item_name'          => 'Dell OptiPlex 7090 Desktop Workstation',
                'category'           => 'Electronics & IT',
                'quantity'           => 25,
                'min_quantity_alert' => 5,
                'unit'               => 'Units',
                'unit_price'         => 750.00,
                'total_cost'         => 18750.00,
                'location'           => 'Computer Lab 1',
                'item_condition'     => 'New / Excellent',
                'status'             => 'In Use',
                'purchase_date'      => Carbon::now()->subMonths(3)->format('Y-m-d'),
                'supplier_name'      => 'TechCorp Solutions Ltd.',
                'supplier_contact'   => '+1 (555) 234-5678',
                'invoice_no'         => 'INV-2026-8841',
                'payment_status'     => 'Paid',
                'payment_method'     => 'Bank Transfer',
                'image_proof'        => 'https://images.unsplash.com/photo-1587831990711-23ca6441447b?w=600&auto=format&fit=crop&q=80',
                'image_proof_type'   => 'Invoice/Receipt',
                'notes'              => 'Intel i7 11th Gen, 16GB RAM, 512GB SSD. Warranty valid until 2029.',
            ],
            [
                'item_code'          => 'INV-FUR-204',
                'item_name'          => 'Student Dual Wooden Desk & Chair Set',
                'category'           => 'Furniture',
                'quantity'           => 120,
                'min_quantity_alert' => 15,
                'unit'               => 'Sets',
                'unit_price'         => 85.00,
                'total_cost'         => 10200.00,
                'location'           => 'Classrooms (Grade 5 - Grade 10)',
                'item_condition'     => 'Good',
                'status'             => 'In Use',
                'purchase_date'      => Carbon::now()->subMonths(6)->format('Y-m-d'),
                'supplier_name'      => 'Apex School Furniture Co.',
                'supplier_contact'   => '+1 (555) 987-6543',
                'invoice_no'         => 'INV-2025-4102',
                'payment_status'     => 'Paid',
                'payment_method'     => 'Cheque',
                'image_proof'        => 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=600&auto=format&fit=crop&q=80',
                'image_proof_type'   => 'Physical Item Photo',
                'notes'              => 'Heavy-duty steel frame with laminated teak wooden tops.',
            ],
            [
                'item_code'          => 'INV-LAB-305',
                'item_name'          => 'Compound Binocular Microscope 1000x',
                'category'           => 'Lab Equipment',
                'quantity'           => 15,
                'min_quantity_alert' => 3,
                'unit'               => 'Pcs',
                'unit_price'         => 320.00,
                'total_cost'         => 4800.00,
                'location'           => 'Biology & Science Lab',
                'item_condition'     => 'New / Excellent',
                'status'             => 'Available',
                'purchase_date'      => Carbon::now()->subMonths(1)->format('Y-m-d'),
                'supplier_name'      => 'Scientific Lab Supplies Direct',
                'supplier_contact'   => '+1 (555) 345-6789',
                'invoice_no'         => 'INV-2026-1190',
                'payment_status'     => 'Paid',
                'payment_method'     => 'Credit Card',
                'image_proof'        => 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&auto=format&fit=crop&q=80',
                'image_proof_type'   => 'Delivery Proof',
                'notes'              => 'LED illumination, 4 objective lenses. Includes dust covers and slides.',
            ],
            [
                'item_code'          => 'INV-ST-408',
                'item_name'          => 'A4 Multipurpose Copy Paper (80 GSM)',
                'category'           => 'Stationery',
                'quantity'           => 4,
                'min_quantity_alert' => 10,
                'unit'               => 'Boxes',
                'unit_price'         => 35.00,
                'total_cost'         => 140.00,
                'location'           => 'Central Store Room',
                'item_condition'     => 'Good',
                'status'             => 'Low Stock',
                'purchase_date'      => Carbon::now()->subDays(15)->format('Y-m-d'),
                'supplier_name'      => 'Office Depot Express',
                'supplier_contact'   => '+1 (555) 456-7890',
                'invoice_no'         => 'INV-2026-9051',
                'payment_status'     => 'Paid',
                'payment_method'     => 'Cash',
                'image_proof'        => 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&auto=format&fit=crop&q=80',
                'image_proof_type'   => 'Invoice/Receipt',
                'notes'              => 'Stock is running low! Needs reorder of 50 boxes for exams.',
            ],
            [
                'item_code'          => 'INV-IT-512',
                'item_name'          => 'Epson Pro 4K Ceiling Mount Projector',
                'category'           => 'Electronics & IT',
                'quantity'           => 8,
                'min_quantity_alert' => 2,
                'unit'               => 'Units',
                'unit_price'         => 650.00,
                'total_cost'         => 5200.00,
                'location'           => 'Auditorium & Smart Classrooms',
                'item_condition'     => 'Good',
                'status'             => 'In Use',
                'purchase_date'      => Carbon::now()->subMonths(4)->format('Y-m-d'),
                'supplier_name'      => 'TechCorp Solutions Ltd.',
                'supplier_contact'   => '+1 (555) 234-5678',
                'invoice_no'         => 'INV-2025-7712',
                'payment_status'     => 'Paid',
                'payment_method'     => 'Bank Transfer',
                'image_proof'        => 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&auto=format&fit=crop&q=80',
                'image_proof_type'   => 'Physical Item Photo',
                'notes'              => 'HDMI & Wireless connection supported. Installed on ceiling mounts.',
            ],
            [
                'item_code'          => 'INV-SPT-601',
                'item_name'          => 'Mikasa Official Volleyball & Net Equipment',
                'category'           => 'Sports Goods',
                'quantity'           => 12,
                'min_quantity_alert' => 4,
                'unit'               => 'Sets',
                'unit_price'         => 60.00,
                'total_cost'         => 720.00,
                'location'           => 'Sports Room & Gymnasium',
                'item_condition'     => 'Good',
                'status'             => 'Available',
                'purchase_date'      => Carbon::now()->subMonths(2)->format('Y-m-d'),
                'supplier_name'      => 'Champion Sports Wear',
                'supplier_contact'   => '+1 (555) 567-8901',
                'invoice_no'         => 'INV-2026-3310',
                'payment_status'     => 'Paid',
                'payment_method'     => 'Cash',
                'image_proof'        => 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=600&auto=format&fit=crop&q=80',
                'image_proof_type'   => 'Physical Item Photo',
                'notes'              => 'Includes 10 official match balls, 2 regulation nets, and ball pump.',
            ],
            [
                'item_code'          => 'INV-FUR-702',
                'item_name'          => 'Ergonomic Executive Swivel Chair',
                'category'           => 'Furniture',
                'quantity'           => 18,
                'min_quantity_alert' => 3,
                'unit'               => 'Units',
                'unit_price'         => 140.00,
                'total_cost'         => 2520.00,
                'location'           => 'Staff Room & Principal Office',
                'item_condition'     => 'Damaged / Repair Needed',
                'status'             => 'Maintenance',
                'purchase_date'      => Carbon::now()->subMonths(8)->format('Y-m-d'),
                'supplier_name'      => 'Apex School Furniture Co.',
                'supplier_contact'   => '+1 (555) 987-6543',
                'invoice_no'         => 'INV-2025-2201',
                'payment_status'     => 'Paid',
                'payment_method'     => 'Bank Transfer',
                'image_proof'        => 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?w=600&auto=format&fit=crop&q=80',
                'image_proof_type'   => 'Physical Item Photo',
                'notes'              => '2 chairs require hydraulic cylinder replacement under warranty.',
            ],
        ];

        foreach ($items as $item) {
            Inventory::updateOrCreate(['item_code' => $item['item_code']], $item);
        }
    }
}
